export { default as Header } from './Header';
export { default as Nav } from './Nav';
export { default as Main } from './Main';
export { default as Footer } from './Footer';
export { default as Charset } from './Charset';
export { default as Create } from './Create';
export { default as Mint } from './Mint';
export { default as Pallete } from './Pallete';
export { default as Render } from './Render';